spring.application.name=portafolio
spring.datasource.url=your_database_url
spring.datasource.username=neondb_owner
spring.datasource.password=npg_q7y1YlAbdugO


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=never

